apiVersion: apps/v1
kind: Deployment
metadata:
  name: brooks-react-app
  labels:
    app: brooks-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brooks-react-app
  template:
    metadata:
      labels:
        app: brooks-react-app
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - gke-low-cost-cluster-default-pool-04626fef-gvbc
      containers:
      - name: brooks-react-app
        image: IMAGE_URL  # This will be replaced with the full image name from Jenkins
        imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: brooks-app-service
spec:
  type: LoadBalancer
  selector:
    app: brooks-react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: brooks-managed-cert
spec:
  domains:
  - www.brooks-dusura.uk

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brooks-ingress
  annotations:
    networking.gke.io/managed-certificates: brooks-managed-cert
spec:
  rules:
  - host: www.brooks-dusura.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brooks-frontend-service
            port:
              number: 80
  tls:
  - hosts:
    - www.brooks-dusura.uk

