apiVersion: apps/v1
kind: Deployment
metadata:
  name: brooks-react-app
  labels:
    app: brooks-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brooks-react-app
  template:
    metadata:
      labels:
        app: brooks-react-app
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - gke-low-cost-cluster-default-pool-04626fef-gvbc
      containers:
      - name: brooks-react-app
        image: IMAGE_URL  # This will be replaced with the full image name from Jenkins
        imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: brooks-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: brooks-react-app  


